### PR TITLE
responseRecorders should implement io.ReaderFrom

### PR DESCRIPTION
**Pull request by dragonsinth**
https://github.com/signalsciences/sigsci-module-golang/issues/9

### CODE REVIEW

**Comment by jhump** [comment]
@brectanus-sigsci, any chance you could review this or assign a reviewer?

**Review by brectanus-sigsci — APPROVED** [review]
LGTM

**Comment by brectanus-sigsci** [comment]
Sorry it took so long :)

**Comment by dragonsinth** [comment]
Thanks @brectanus-sigsci !  No worries... this was actually pretty fast compared to this one I just landed... https://github.com/rails/rails/pull/18496 😂

**Pull request merged**
