### PR TITLE
allow graphql content-types

### PR DESCRIPTION
**Pull request by vcarvajal-sigsci**

### CODE REVIEW

**Review by amacnair — DISMISSED** [review]
LGTM

**Review by brectanus-sigsci — COMMENTED** [review]
LGTM. You will need to adjust the `VERSION` (should be a minor bump) and add to the `CHANGELOG.md` to release, though.

**Review by amacnair — COMMENTED** [review]
I think `version.go` also needs a version bump

**Review by amacnair — APPROVED** [review]
LGTM

**Pull request merged**
